from __future__ import annotations

from typing import Any, Protocol

from ..models import Dataset, DatasetSummary, Resource


class OpenDataProvider(Protocol):
    name: str
    title: str
    type: str

    async def search(self, query: str, rows: int = 20, start: int = 0) -> list[DatasetSummary]: ...
    async def dataset(self, dataset_id: str) -> Dataset: ...
    async def resource(self, resource_id: str) -> Resource: ...
    async def groups(self) -> list[dict[str, Any]]: ...
    async def organizations(self) -> list[dict[str, Any]]: ...
    async def tags(self) -> list[str]: ...
    async def datastore_preview(self, resource_id: str, limit: int = 10) -> dict[str, Any]: ...
