from __future__ import annotations

from typing import Any, Protocol


class OpenDataProvider(Protocol):
    name: str
    title: str

    async def search(self, query: str, rows: int = 20, start: int = 0) -> dict[str, Any]: ...
    async def dataset(self, dataset_id: str) -> dict[str, Any]: ...
    async def groups(self) -> list[dict[str, Any]]: ...
    async def organizations(self) -> list[dict[str, Any]]: ...
    async def tags(self) -> list[str]: ...
    async def datastore_preview(self, resource_id: str, limit: int = 10) -> dict[str, Any]: ...
